name: Continuous Integration

on: [push]

jobs:
  vendor:
    name: Vendor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go mod download

  test:
    name: Test
    needs: vendor
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        # TODO: Figure out can this be extracted into a common variable at
        # the top of the file, so its easier to update.
        - "1.19"
        - "1.18"
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go test ./...


  lint:
    name: Lint
    needs: vendor
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: golangci/golangci-lint-action@v3

  build:
    name: Build
    needs: vendor
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
        go:
        - "1.19"
        - "1.18"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: go build ./...
